# Generated by Django 4.0.6 on 2022-09-14 18:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cohortapplication_techsiqteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='techsiqteam',
            name='image',
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='techsiqteam',
            name='detailsInfo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
